-- Drop existing tables
DROP TABLE IF EXISTS substitutions;
DROP TABLE IF EXISTS timetable;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS users;

-- Users Table (HOS & Faculty)
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    faculty_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    department TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT CHECK(role IN ('hos', 'faculty')) NOT NULL
);

-- Branches Table
CREATE TABLE branches (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    department TEXT NOT NULL,
    branch_name TEXT NOT NULL,
    year TEXT NOT NULL,
    section TEXT NOT NULL,
    hos_id INTEGER,
    FOREIGN KEY(hos_id) REFERENCES users(id)
);

-- Subjects Table
CREATE TABLE subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    subject_code TEXT UNIQUE NOT NULL,
    subject_name TEXT NOT NULL,
    department TEXT NOT NULL
);

-- Official Timetable Table
CREATE TABLE timetable (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    branch_id INTEGER NOT NULL,
    day TEXT CHECK(day IN ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday')) NOT NULL,
    period INTEGER NOT NULL,
    start_time TEXT,
    end_time TEXT,
    subject_id INTEGER NOT NULL,
    faculty_id INTEGER NOT NULL,
    room TEXT,
    FOREIGN KEY(branch_id) REFERENCES branches(id),
    FOREIGN KEY(subject_id) REFERENCES subjects(id),
    FOREIGN KEY(faculty_id) REFERENCES users(id)
);

-- Substitutions Table
CREATE TABLE substitutions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timetable_id INTEGER NOT NULL,
    date TEXT NOT NULL, -- Format: YYYY-MM-DD
    original_faculty_id INTEGER NOT NULL,
    substitute_faculty_id INTEGER NOT NULL,
    status TEXT DEFAULT 'assigned',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(timetable_id) REFERENCES timetable(id),
    FOREIGN KEY(original_faculty_id) REFERENCES users(id),
    FOREIGN KEY(substitute_faculty_id) REFERENCES users(id)
);

-- Demo Data Insertion

-- Password hash for 'password123'
-- Hash generated by bcryptjs
INSERT INTO users (faculty_id, full_name, email, phone, department, password_hash, role) VALUES
('HOS001', 'Dr. Smith', 'smith@college.edu', '1234567890', 'CSE', '$2a$10$mzgNO7vjCvc5p1aQ7Xl4HuDRGyCzFl5cI7S0tUHo6r.SuDQD7rjB2', 'hos'),
('FAC001', 'Dr. Ravi', 'ravi@college.edu', '0987654321', 'CSE', '$2a$10$mzgNO7vjCvc5p1aQ7Xl4HuDRGyCzFl5cI7S0tUHo6r.SuDQD7rjB2', 'faculty'),
('FAC002', 'Dr. Anitha', 'anitha@college.edu', '1112223333', 'CSE', '$2a$10$mzgNO7vjCvc5p1aQ7Xl4HuDRGyCzFl5cI7S0tUHo6r.SuDQD7rjB2', 'faculty'),
('FAC003', 'Prof. Kiran', 'kiran@college.edu', '4445556666', 'CSE', '$2a$10$mzgNO7vjCvc5p1aQ7Xl4HuDRGyCzFl5cI7S0tUHo6r.SuDQD7rjB2', 'faculty'),
('FAC004', 'Prof. Priya', 'priya@college.edu', '7778889999', 'CSE', '$2a$10$mzgNO7vjCvc5p1aQ7Xl4HuDRGyCzFl5cI7S0tUHo6r.SuDQD7rjB2', 'faculty');

INSERT INTO branches (department, branch_name, year, section, hos_id) VALUES
('CSE', 'CSE-A', 'III Year', 'A', 1),
('CSE', 'CSE-B', 'III Year', 'B', 1);

INSERT INTO subjects (subject_code, subject_name, department) VALUES
('CS301', 'DBMS', 'CSE'),
('CS302', 'OS', 'CSE'),
('CS303', 'CN', 'CSE'),
('CS304', 'Java', 'CSE');

-- Demo Timetable for CSE-A
-- Monday
INSERT INTO timetable (branch_id, day, period, start_time, end_time, subject_id, faculty_id, room) VALUES
(1, 'Monday', 1, '09:00', '10:00', 1, 2, 'Room 101'), -- DBMS - Ravi
(1, 'Monday', 2, '10:00', '11:00', 2, 5, 'Room 101'), -- OS - Priya
(1, 'Monday', 3, '11:00', '12:00', 3, 4, 'Room 101'); -- CN - Kiran

-- Tuesday
INSERT INTO timetable (branch_id, day, period, start_time, end_time, subject_id, faculty_id, room) VALUES
(1, 'Tuesday', 1, '09:00', '10:00', 4, 2, 'Room 101'), -- Java - Ravi
(1, 'Tuesday', 2, '10:00', '11:00', 1, 5, 'Room 101'); -- DBMS - Priya

-- Demo Timetable for CSE-B (so some faculty are busy)
-- Monday
INSERT INTO timetable (branch_id, day, period, start_time, end_time, subject_id, faculty_id, room) VALUES
(2, 'Monday', 1, '09:00', '10:00', 2, 5, 'Room 102'), -- OS - Priya (Busy Mon P1)
(2, 'Monday', 2, '10:00', '11:00', 3, 4, 'Room 102'); -- CN - Kiran (Busy Mon P2)

-- In this setup, for Monday Period 2:
-- CSE-A has OS (Priya). CSE-B has CN (Kiran).
-- If Ravi (who is free Mon P2) wants to be substitute for someone... wait, let's say Priya wants a substitute for Monday Period 2.
-- Priya is busy. Kiran is busy (CSE-B).
-- Ravi is free. Anitha is free.
